name: Publish Python SDK to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the Python SDK to release"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools build twine

      - name: Set Version
        run: |
          echo "Setting version to ${{ inputs.version }}"
          sed -i "s/version=.*/version='${{ inputs.version }}',/" setup.py

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m twine upload --non-interactive --repository pypi dist/* -u __token__ -p $PYPI_TOKEN
